name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      - "!main"
    tags-ignore:
      - "*"

jobs:
  build:
    uses: magic-dev-tools/github-workflow-templates/.github/workflows/build-monorepo.yaml@main
